### ISSUE TITLE
Does not compile - Missing dependency codecov

### ISSUE THREAD

**Issue by Kynneb** [ESROCOS/gui-vizkit3d_tastelib#1]
Breaks at compile time:

```
CMake Error at CMakeLists.txt:16 (find_package):
  By not providing "Findcodecov.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "codecov", but
  CMake did not find one.
```

It seems, dependency codecov is required in the CMakeList but not advertised to autoproj.

**Comment by Kynneb** [comment]
Is that the codecov project used? https://github.com/RWTH-HPC/CMake-codecov

Following their guide the code compiles, but perhaps you might have a look into that as well.

**Comment by mmunoz-gmv** [comment]
I had forgotten to push the cmake modules added to the buildconf package, where codecov is added. It's in the master branch.

**Comment by Kynneb** [comment]
Thanks for the quick response, but please push to the integration branch (or some new branch) the next time. Direct committing to the master makes reviewing/testing extremely difficult.
