### ISSUE TITLE
'asn1Scc_Vector3d_toAsn1' was not declared in this scope

### ISSUE THREAD

**Issue by Kynneb** [ESROCOS/gui-vizkit3d_tastelib#6]
When trying a fresh install of ESROCOS I get this error - might it be that this is due to the latest update in the types-base_support OpaqueConversions.hpp?

When reverting base_support to 64c922 it seems to work.

**Comment by RaquelJalvo** [comment]
Now it should be fixed. These functions were added manually and the last time I generated the library I forgot to add it. Thank you!!

**Comment by Kynneb** [comment]
Thanks for your response - I started a new build and will follow up on how things turned out.

**Comment by Kynneb** [comment]
That worked fine, thanks again.
